{{ config(materialized='table') }}

SELECT DISTINCT
    ORDERDATE AS DATE,
    YEAR(ORDERDATE) AS YEAR,
    MONTH(ORDERDATE) AS MONTH,
    MONTHNAME(ORDERDATE) AS MONTH_NAME,
    DAY(ORDERDATE) AS DAY,
    DAYNAME(ORDERDATE) AS DAY_NAME,
    WEEK(ORDERDATE) AS WEEK

FROM {{ ref('orders_clean') }}